language: c
compiler: clang
cache: ccache
git:
  submodules: false


stages:
  - test
  - downstream

jobs:
  include:
    - stage: test
      os: linux
      dist: trusty
      sudo: required
      before_install:
        - travis_wait 30 git submodule update --init llvm
        - travis_wait 30 git submodule update --init --depth=50
    - stage: test
      os: osx
      osx_image: xcode10.2
      before_install:
        - travis_wait 30 git submodule update --init llvm
        - travis_wait 30 git submodule update --init --depth=50
        - mkdir -p ~/.local/bin
        - mkdir ~/junit
        - export PATH=/usr/local/opt/ccache/libexec:$HOME/.local/bin:$PATH
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install gnu-sed ccache e2fsprogs
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install binutils
        - brew upgrade binutils
        - pip install --user yamlish junit_xml
        - ln -sf /usr/local/bin/gsed ~/.local/bin/sed
        - ln -sf /usr/local/bin/gdate ~/.local/bin/date
        - ln -sf /usr/local/opt/e2fsprogs/sbin/mkfs.ext4 ~/.local/bin/
        - ln -sf /usr/local/opt/binutils/bin/objcopy ~/.local/bin/objcopy
    - stage: downstream
      script: bash -ex ./.travis-trigger.sh ukontainer/rumprun-packages lkl-musl
      os: linux

script:
  - sudo mkdir -p /opt/rump && sudo chown -R $USER /opt/
  - for file in `find patches/ -maxdepth 1 -type f` ; do patch -p1 < $file ; done
  - for file in `find patches/$TRAVIS_OS_NAME/ -maxdepth 1 -type f` ; do patch -p1 < $file ; done
  - ./build.sh -d /opt/rump -q -k linux notest
  - RUMPDIR=/opt/rump RUMPOBJ=`pwd`/rumpobj make -C tests run
  - bash -ex ./.travis-deploy.sh
